server:
    port: 18080

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017
            auto-index-creation: true
            database: chat-logger
        redis:
            host: localhost
            port: 6379
            database: 0
            connect-timeout: 3s
            timeout: 3s

            lettuce:
              pool:
                  min-idle: 0
                  max-idle: 8
                  max-active: 8
                  max-wait: -1ms
    mail:
        host: smtp.gmail.com
        port: 587
        username: arlenzhang0308@gmail.com
        password: slikcqsqpltnqdvm
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret: 541FDSFDsdbaf513fdsv351afs3d35a1sSD1323fs21d31ds531S51DSF
    expiration: 864000000